klen/graphite-beacon

README.md, graphite_beacon/alerts.py
Allow configuring the Graphite query time window (ie. the time period to fetch data from, that is the `from=-<time_window>` parameter) separately from the query interval. This allows for frequent polling while providing some smoothing of the data. For example, to poll once every minute but look at the sum over the past 5 minutes:
"interval": "1m",
"time_window": "5m",
"method": "sum"
If undefined, `time_window` defaults to `interval` so the existing functionality remains unchanged.
=> Configurable time window for graphite queries

graphite_beacon/alerts.py
`sum` is documented but it doesn't actually work because it's missing from
the `METHODS` constant
=> alerts: add "sum" to METHODS

graphite_beacon/alerts.py, graphite_beacon/graphite.py
The current behavior is to raise exception in the constructor of the GraphiteRecord object when a metric with zero values is loaded. This causes all of the other metrics (which could be fine) not to be loaded. In the example render API output for our disk usage gauges, the machine `disk.east.app2' is reporting metrics anymore after a statsd reset so gauge was reset. It would make the load of all of the other metrics fail.
disk.east.app1,1421711710,1421711770,10|44.0,44.0,44.0,44.0,44.0,None
disk.east.app2,1421711710,1421711770,10|None,None,None,None,None,None
disk.east.app3,1421711710,1421711770,10|29.0,29.0,29.0,29.0,29.0,None
disk.east.app4,1421711710,1421711770,10|56.0,56.0,56.0,56.0,56.0,None
The proposed change here sets a flag on the GraphiteRecord object if it does not contain any …
=> Change no data behavior

graphite_beacon/core.py, tests.py
Fixes an issue where the already configured alerts were combined with the alerts
in the configuration file that was being reparsed in response to a SIGHUP.
Fixes #28
=> Don't duplicate alerts when reloading configuration.

graphite_beacon/core.py, tests.py
Fixes an issue in Python 2.6 where the logging.Logger.setLevel method did not
convert textual log levels to the numeric log levels, but the same method in
Python 2.7 did.
Fixes #31.
=> Explicitly convert textual log level names to numeric log levels.

README.md, graphite_beacon/alerts.py, graphite_beacon/core.py
New 'no_data' config value can now be set to 'normal', 'warning' or 'critical' at the top-level, or per alert. Default retains the same behavior as today: 'critical' alerts. Includes associated readme updates.
I'm using statsd to keep track of a few metrics like 'crashes', 'deploys' and 'launches.' Whenever these are non-zero, I want a notification. As you might expect, I only send data from my scripts and apps when it's non-zero. Statsd takes care of this for me, by remembering the data point after I initially send it, sending zeros thereafter (this is configurable, of course).
When I need to restart statsd or the entire machine, those data points are no longer known to statsd. Today I get critical alerts whenever this happens. This allows that logging level for 'no data' to be …
=> Add ability to customize alert behavior with no data

graphite_beacon/handlers/cli.py
It happens when no data was received for graphite parameter or URL check failed.
=> Fix #46: Rule can be not set in notification

graphite_beacon/handlers/__init__.py, graphite_beacon/handlers/victorops.py
Simple VictorOps handler implemented using their REST endpoint. It's really a copy of the HTTP handler already present. But since VictorOps has useful specific keys and a JSON body, I thought it would be better to keep the current HTTP handler generic as is.
Just two keys are needed to enable the handler:
```js
{
...
"victorops": {
"endpoint": "http://myendpoint.com",
// optional - defaults to "everyone"
"routing_key": "everyone",
}
...
}
```
More info:
https://victorops.com/
http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/?l=en_US&fs=Search&pn=1
=> VictorOps handler via the REST Endpoint.

example-config.json
Just a simple English correction in `example-config.json`: Comments "are" allowed here
=> English correction: Comments "are" allowed here

README.md, graphite_beacon/alerts.py, graphite_beacon/core.py, graphite_beacon/handlers/opsgenie.py, tests.py
Allow a different "external" URL for when alerts are sent. 
Something similar exists in the SMTP email handler by allowing another `graphite_url` parameter, so this pulls it out into the root configuration level to make it available for all handlers.
=> Add 'public_graphite_url' config option for external handlers

graphite_beacon/alerts.py
Checking can be disabled by setting "validate_cert": false
Default is true.
This is useful for checking URL's within your environment which have some specific entries where the URL doesn't match the certificate.
=> Added support for url-checking on urls with invalid SSL certificates.

graphite_beacon/alerts.py
Need to explicitly specify `graphite_url` kwarg when setting `self.url` otherwise `public_graphite_url` will get used to fetch metrics.
=> Fix bug where public_graphite_url was being used to fetch metrics incorrectly

graphite_beacon/alerts.py, graphite_beacon/core.py
i have seen lots of timeout (599) error when running graphite-beacon with ~ 700 metrics. the reason seems because of the default connect timeout (20 seconds in based on http://tornado.readthedocs.org/en/latest/_modules/tornado/httpclient.html) may not be enough if the graphite-beacon have lots of metrics to check.
=> allow customize the connect_timeout

graphite_beacon/handlers/slack.py
Allow notifications to slack users too.
If the channel name starts with @ the notification(s) will be sent to the specified slack user.
=> Allow notifications to slack users too.

graphite_beacon/alerts.py
Currently validate_cert is only used in URLAlert, but not in GraphiteAlert. This change will reuse the same variable when connecting to Graphite server.
=> Use validate_cert when accessing Graphite

graphite_beacon/handlers/pagerduty.py
Small improvements to the pagerduty handler:
- add extra values to the incident key (level, alert and target if available)
- set client_url to the graphite graph url
=> client_url and detailed incident key in pagerduty handler

.travis.yml, README.md, graphite_beacon/handlers/telegram.py, graphite_beacon/handlers/untitled.py
Implements #130 
Fixes #127 
Fixes #129 
Some methods return bytes on python3 which was reason of TypeError during json serialization.
Simply using bytes.decode() was enough.
Also removed str.encode() method, which returns bytes on python3 and fixed key error (sometimes handler receives update without 'text' field).
=> make telegram handler persist chats/groups across sessions, fix json serialization bug, fix key error

Dockerfile
The development version now tries to load config.json from / (instead of
/srv/alerting/etc as before). Just not to break anyone's existing
deployment, this fix adds a default config.json that does nothing but
include /srv/alerting/etc/config.json.
This way, mounting either `/config.json` (new behaviour) or
`/srv/.../config.json` (old behaviour) works.
=> Add default backward-compatible /config.json

Makefile, graphite_beacon/alerts.py, graphite_beacon/app.py, graphite_beacon/core.py, graphite_beacon/graphite.py, graphite_beacon/handlers/cli.py, graphite_beacon/handlers/hipchat.py, graphite_beacon/handlers/http.py, graphite_beacon/handlers/log.py, graphite_beacon/handlers/pagerduty.py, graphite_beacon/handlers/slack.py, graphite_beacon/handlers/smtp.py, graphite_beacon/handlers/telegram.py, graphite_beacon/handlers/victorops.py, graphite_beacon/template.py, graphite_beacon/units.py, graphite_beacon/utils.py, pytest.ini, tests/integration/graphite_test.py, tests/unit/alerts_test.py, tests/unit/handlers/smtp_test.py, tests/unit/units_test.py, tests/unit/utils_test.py, tests/util.py, tox.ini
* Fixes bug on py3 with string decode
* Fixes bug with not respecting `time_window` on global params
* Orders imports
* Better error message when parsing a graphite metric fails
* Something resembling an integration test
=> Add simple integration test and misc fixes

graphite_beacon/handlers/slack.py
Mattermost tries to be API-compatible with Slack, but does not (currently) support incoming webhooks in JSON format without the 'Content-Type': 'application/json' header.  Given that the [Slack API documentation](https://api.slack.com/incoming-webhooks) (not to mention [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5)) also specifies a preference for content type to be made explicit, adding the header here seems like reasonable way to make the webhooks handler work for Mattermost while continuing to work for Slack.
=> Add Content-Type header to slack request for mattermost compatibility
